// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApHspMUDjr1SHAQTekOkDzjt3G79GyhKk',
    appId: '1:133620509973:web:0acad6711af4f70d79cd1c',
    messagingSenderId: '133620509973',
    projectId: 'sentionet',
    authDomain: 'sentionet.firebaseapp.com',
    storageBucket: 'sentionet.firebasestorage.app',
    measurementId: 'G-V2P5XZF1VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjl-eyo6hgS_WjtXE9SE__c0wp7rKWrl0',
    appId: '1:133620509973:android:6638ae01a6804a4479cd1c',
    messagingSenderId: '133620509973',
    projectId: 'sentionet',
    storageBucket: 'sentionet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf4MndDQSidmqfPKmaR8OvgLWaBDNCizw',
    appId: '1:133620509973:ios:0f9799253b637f3879cd1c',
    messagingSenderId: '133620509973',
    projectId: 'sentionet',
    storageBucket: 'sentionet.firebasestorage.app',
    iosClientId: '133620509973-i6hi75cruje32ss98ohvhfrnnhlsitgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentionetDraft3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf4MndDQSidmqfPKmaR8OvgLWaBDNCizw',
    appId: '1:133620509973:ios:0f9799253b637f3879cd1c',
    messagingSenderId: '133620509973',
    projectId: 'sentionet',
    storageBucket: 'sentionet.firebasestorage.app',
    iosClientId: '133620509973-i6hi75cruje32ss98ohvhfrnnhlsitgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentionetDraft3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApHspMUDjr1SHAQTekOkDzjt3G79GyhKk',
    appId: '1:133620509973:web:bb6f85adb083892779cd1c',
    messagingSenderId: '133620509973',
    projectId: 'sentionet',
    authDomain: 'sentionet.firebaseapp.com',
    storageBucket: 'sentionet.firebasestorage.app',
    measurementId: 'G-VFBZHWVP1L',
  );

}